# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Services/Catalog/Catalog.API/Dockerfile'
        tags: |
          $(tag)
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    additionalDockerComposeFiles: '**/docker-compose.override.yml'
    dockerComposeFileArgs: |
      POSTGRES_USER="admin"
      POSTGRES_PASSWORD="admin123"
      PGADMIN_DEFAULT_EMAIL="admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD="admin123"
      ASPNETCORE_ENVIRONMENT="Development"
    action: 'Run services'