version: '3.4'

services:
  catalogDB:
    container_name: catalogDB
    restart: always
    ports:
    - 27017:27017 
    volumes:
    - mongoData:/data/db
  catalog.api:
    container_name: catalog.api
    depends_on: 
    - catalogDB
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DataBaseSetting:CnxString=mongodb://catalogDB:27017
    ports:
      - 8000:80