version: '3.4'

services:
  catalogDB:
    image: mongo
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketDB:
    image: redis:alpine
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  DiscountDB:
    image: postgres

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
  discount.gprc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce


volumes:
  mongoData:
  portainer_data:
  postgres_data:
  pgadmin_data:
